---
title: "Content modelization, recognition and optimization, a state of the art"
author: "JJ Merelo, University of Granada"
date: "5/5/2021"
output:
  word_document: default
  html_document:
    df_print: paged
  pdf_document:
    keep_tex: yes
bibliography: 
  - trope-recognition.bib
  - geneura.bib
  - report.bib
  - bibliography-plos.bib
  - uex.bib
  - bigredbutton.bib
  
abstract: Engineering content is starting to be possible under the twin pushes of machine learning, as well as natural (and other) language processing. Generally, from the raw material that is the manuscript (or music score) we will need to reach a higher-level representation, so that it can be first scored or analyzed, and eventually optimized via the generation of a series of suggestions. The fact that there are multiple layers of meaning in manuscript or scores, and that different emotions are going to be transmitted, implies that there's no best, or single, way of doing it. Here we will present an overview of the different methodologies that have been used so far, and suggest current research themes and venues for future work.
---

## Introduction


<!-- Descripción del estado actual de conocimiento y desarrollos en el ámbito temático específico de la propuesta -->

Any kind of content with an artistic intention contains a series of patterns that constitute its *language* and that can be employed to build a work of art. These patterns are called, in the case of narrative media, *tropes* [@simpsons].

A trope is a pattern or cliché used by creators to express some idea and which have been proven effective in previous works. For example, the *Hero's Journey*, in which a young hero is called to adventure, receives a weapon from an old mentor, and together with his new friends, defeats the bad guys and returns as a hero. This idea has been repeated from ancient times, as in *The Odyssey*, to more recent stories, such as *Ready Player One*.

<!-- ESTO ES DEL PAPER DE PLOS. Para el paper habrá que refrasearlo -->

There are available in the literature some works studying specific tropes in film and media studies. For example in [@Barrowman19film] action films tropes are discussed, including characters tropes (cop, cowboy), actions (chase, last minute rescue) and techniques (for example, camera shaking movement). More works have focused in other kind of tropes, such as the trope of the *Zombies* [@Web08Zombie], scenes that take place in a museum [@fisher2002museal],  or even as specific as the Brazilian housemaid [@Oliveira2020brazilian]. 

This is why the study of the interactions between these tropes in different media, such as films, can be useful to creators or academics in a wide variety of situations, in besides the mere descriptive analysis.

There is currently a website called TVTropes.org with more than 20,000 tropes and the films in which they appear. In our previous project we downloaded the information from this website, and, in combination with movie information from the IMDB website (average rating and number of votes) we were able to create a dataset with more than 10,000 movies and more than 20,000 associated tropes.


<!-- Descripción del conocimiento, idea o resultado derivado o relacionado con el proyecto anterior y que se propone para la prueba de concepto  -->

This dataset was initially used by researchers of this project in [@doi:10.1111/exsy.12525] to train a system based on neural networks to predict the rating and popularity of a movie from the tropes that appear in it. Once this model was obtained, an optimization algorithm was developed that, from a fixed set of tropes, finds the remaining tropes that can best match this set by maximizing the score or popularity.

Later, in the work [@simpsons] we developed a system to find the relationships that exist between these tropes, and how these combinations influence rating and popularity. To do so, we used different algorithms from the field of bibliometrics to find the different communities of tropes. In addition, using a Strategic diagram [@CoboMJ-scimat-2012] we were able to find the degree of development of each of these communities: *motor*, *transverse*, *specialized* or *emerging*.

This work gained a lot of attention outside the academic environment and as a result of it we obtained different expressions of interest from different companies related to the world of cinema.

<!-- ESTO TAMBIEN ES DEL PAPER DE PLOS -->

However, there is a lack of works dealing with complex network analysis in the field of creative media such as films. In [@Waumans15topology], authors use a complex network of interactions between literary characters (specifically, the Harry Potter saga) to compute their relationships to see how they evolve throughout their story. Using text extraction algorithms from novels, they generate different social networks from the dialogues. These networks are used to measure some characteristics related to the author's style, and to the book's story. Amancio [@Amancio2016] proposed the use of co-occurrence networks to study and detect the different entities (characters or locations) and their semantic relationships, which appear in different novels. A topological analysis was applied to obtain patterns that were not possible to detect using classical methods. 

However, as stated before, these works rely on the analysis of whole texts to obtain the relationships between entities, whereas our work is based on the mere occurrence of tropes in the different films.

To our knowledge, except for our work mentioned above, there is no other work that uses automatic analysis or machine learning to extract knowledge from the set of tropes, and automatically propose ideas to creatives, such as screenwriters.

<!-- AQUI IRA LO DE UEX -->

The term “trope (or tropus)” can be also considered in music, when referred to “melismas” to certain music motives, sections, even texts associated to songs, or combinations of any of them.  From the 9th century onward, music analysis has considered the evolution of forms considering tropes, although during the 20th century, and because of new types of musics -atonal and serial- the concept may be associated to unordered collection of different pitches.

Every music student nowadays faces two main areas related to music analysis and composition:  on the one hand the study of harmony, and secondly, the analysis of scores.  Both require a deep understanding of composition rules, that are associated to “tropes” understanding, given their relationship to melody creation -that implies using patterns, motives...- and chord progressions, and relationship between voices in a score.

The first task music students face is choral composition, that embodies a number of rules for the proper conduction of 4 voices:  Soprano, Alto, Tenor and Bass.  Beginning with a given melody, students must develop four voices that follow a set of rules that must be learned and applied.  The rules somehow encode all the knowledge and aesthetics that musicians developed along a specific period:  baroque period, classicism, jazz...  The rules embodies all the knowledge associated with proper use of different kind of tropes.
 
We are mainly interested in developing tools that help students with the proper use of tropes in music, when addressing analysis of scores as well as composition.  

In this later area, we may find a number of problems where artificial intelligence is of interest. Music Information Retrieval (MIR) is the area where we can find main developments, that embodies a number of problems of interest.  The leading conference in the area is organized by the International Society for Music Information Retrieval (https://www.ismir.net).  Among the main problems addressed, a number of them are of interest in this context:

* Optical Music Recognition:  Students typically work in notebooks where they wrote their scores. Any tool that face the problem of trope analysis requires first to convert this scores to any avaliable music standard file (such as musicXML).
* Analysis of the score:  The analysis require knowledge about harmony rules to be applied, understanding of the key modulation, etc.
* Music Transcription:  Another important problem for music students is related to transcription:  how to obtain the score from a music audio.

In all these areas we can find different techniques applied.  For instance, in [@Fernandez17CEC] we presented the first Cartesian Genetic Programming approach to transcription of piano music.  Although other techniques have already been applied, the flexibility of the approach, as we as its parallelization capabilities provides unique advantages.

We have also recently developed the first software tool that helps students to find mistakes in the application of harmony rules in SATB composition exercises [@Miragaia21Applied].  [Sharpmony](https://sharpmony.unex.es) was that launch as a help to both students and their teachers.  Since their launch, 13 institutions and more than 1800 students are using the tool

Yet, we still need a layer capable of providing OMR if we want to reach a wide public and convert Sharpmony in the tool every music student will use.  No other available tool provides simultaneously OMR, Score analysis and Transcription.  The addition of this layer would allow to go from the notebook to the analysis in a single step.

<!-- Identificación del problema o la necesidad a los que se dirige la prueba de concepto y cómo la aproximación que se propone podría contribuir a los mismos. -->

Currently, the development of artistic works, such as film scripts, is a complex task, given the large amount of subjectivity that exists in their creation, and the difficulty in predicting the quality and audience reaction. Therefore, the application to be developed in this project is intended to be of interest to the various members that are part of a creative process (for example, in the case of a film would be producers, directors, screenwriters and others). These members have to filter a large number of existing artistic works to find the most interesting for the public, either filtering scripts to shoot, or deciding on which ideas or themes to invest their money.

<!-- Novedad e innovación que aportarían los resultados que se proponen valorizar; indique el estado de madurez de la propuesta (desde la idea a su aplicación). -->

Our system mentioned above is a proof of concept that has shown promising results, allowing us to obtain a metric that indicates how good or popular a movie will be or how good a student music score is or how much it deviates from what was requested and what's needed to make it follow the usual rules. We have also been able to obtain which thematic areas may be more interesting to focus the efforts in development. However, it still needs to be tested with professionals in the creative world. Therefore, it is necessary to develop an experimental methodology with human users who can provide feedback and guide the development to adapt this application to their needs.

To this end, interviews will be conducted to learn about the workflows of the creators, and to adapt our application to this flow. We will develop and use a series of performance metrics that will allow to make the best decision at every moment in the flow. Therefore, the goal is to implement a configurable application in which users can introduce values related to the idea to be developed and automatically obtain a detailed report.

The state of maturity of the current project is as follows

* The Sharpmony application is published and in use by several music schools. However, it needs to be extended with additional computational intelligence by allowing the identification of tropes, and also reading of paper music scores, to make its use easier.
* The framework that optimizes combination of tropes is already published [@startroper], but the extraction of tropes from manuscripts [@chang2021situation] need to be integrated.
* Transfer learning methods and code need to be tested and implemented so that it can be used by both applications.
* We will need better datasets for other languages, if we want to target the application to non-Spanish speaking countries.

<!-- Creo que esto se puede extender mejor y vender más la moto -->

## Similar initiatives and patents

In general, algorithms cannot be patented in Europe; however, there are indeed a series of patents covering parts of the proposal, or in a similar field. For instance, [@narrativespatent] is about automatic characterization of scripted narratives, such as the ones used in movies, and analyzes them automatically covering a series of features. This does not go so far as to create a model that uses tropes, but is indeed a recent patent that follows a divergent route to possibly reach a similar objective; the paper by Mourchid et al. [@Mourchid18] also creates a model of a script, based in this case in character interactions, creating an actual complex network that is used to model the script. Although this kind of work would be extremely interesting for evaluation, and is in fact independent of the language, it does not cover as much ground as a model based on tropes. It could be, however, evaluated for addition within a tool that would include different kinds of models, as well as different kinds of recommendations.

On the other hand, some recent startups are focused on generation of narrative; RivetAI combine man and machine as cocreators; in order to do that, basically language models are used. While this helps to generate narrative, it does not predict or model at a higher level that will help the authors take decisions that will improve the overall quality of the work.

## Conclusions

In this project, we need to analyze sequential art forms (movie scripts and music scores) at a level that allows the system to suggest improvements from machine learning models generated from existing scripts, trope and music features datasets, and grades, reviews, or box office income for the resulting work. In that sense, we will use automatic recognition of those features (tropes or music features), as well as a machine-learned based engines for suggestion of changes that can be used to tutor practitioners in early phases of their career, or industry insiders in every phase of the production.



## References

